"""
This type stub file was generated by pyright.
"""

import torch
from typing import List
from torch import nn

class AdaptiveInput(nn.Module):
    def __init__(self, vocab_size: int, padding_idx: int, initial_dim: int, factor: float, output_dim: int, cutoff: List[int], q_noise: float = ..., qn_block_size: int = ...) -> None:
        ...
    
    def weights_for_band(self, band: int): # -> tuple[Any | Tensor | Module, Any | Tensor | Module]:
        ...
    
    def forward(self, input: torch.Tensor): # -> Any | Tensor:
        ...
    


