"""
This type stub file was generated by pyright.
"""

import torch.nn as nn
import torch

class BaseLayer(nn.Module):
    def __init__(self, args) -> None:
        ...
    
    def forward(self, input_features, *args, **kwargs): # -> tuple[Any, None, None]:
        ...
    
    def inverse_sort(self, order): # -> Tensor:
        ...
    
    def balanced_assignment(self, scores): # -> tuple[Any, None, None]:
        ...
    
    def greedy_assignment(self, scores, k=...): # -> tuple[Any, Any, List[Any]]:
        ...
    
    def load_assignment(self):
        ...
    


class BaseSublayer(nn.Module):
    def __init__(self, args) -> None:
        ...
    
    def forward(self, xs):
        ...
    


class All2All(torch.autograd.Function):
    @staticmethod
    def forward(ctx, xs, input_splits=..., output_splits=...): # -> Tensor:
        ...
    
    @staticmethod
    def backward(ctx, grad_output): # -> tuple[Tensor | Any, None, None]:
        ...
    


