"""
This type stub file was generated by pyright.
"""

import torch.nn as nn

class BeamableMM(nn.Module):
    """This module provides an optimized MM for beam decoding with attention.

    It leverage the fact that the source-side of the input is replicated beam
    times and the target-side of the input is of width one. This layer speeds up
    inference by replacing the inputs {(bsz x 1 x nhu), (bsz x sz2 x nhu)}
    with smaller inputs {(bsz/beam x beam x nhu), (bsz/beam x sz2 x nhu)}.
    """
    def __init__(self, beam_size=...) -> None:
        ...
    
    def forward(self, input1, input2): # -> Tensor:
        ...
    
    def set_beam_size(self, beam_size): # -> None:
        ...
    


