"""
This type stub file was generated by pyright.
"""

import torch
from typing import List, Tuple
from fairseq.data import Dictionary
from torch import nn

CHAR_PAD_IDX = ...
CHAR_EOS_IDX = ...
logger = ...
class CharacterTokenEmbedder(torch.nn.Module):
    def __init__(self, vocab: Dictionary, filters: List[Tuple[int, int]], char_embed_dim: int, word_embed_dim: int, highway_layers: int, max_char_len: int = ..., char_inputs: bool = ...) -> None:
        ...
    
    def prepare_for_onnx_export_(self): # -> None:
        ...
    
    def set_vocab(self, vocab, max_char_len): # -> None:
        ...
    
    @property
    def padding_idx(self): # -> int:
        ...
    
    def reset_parameters(self): # -> None:
        ...
    
    def forward(self, input: torch.Tensor): # -> Tensor | Any:
        ...
    


class Highway(torch.nn.Module):
    """
    A `Highway layer <https://arxiv.org/abs/1505.00387>`_.
    Adopted from the AllenNLP implementation.
    """
    def __init__(self, input_dim: int, num_layers: int = ...) -> None:
        ...
    
    def reset_parameters(self): # -> None:
        ...
    
    def forward(self, x: torch.Tensor): # -> Tensor:
        ...
    


