"""
This type stub file was generated by pyright.
"""

import torch
from torch import Tensor, nn

class ConvTBC(torch.nn.Module):
    """1D convolution over an input of shape (time x batch x channel)

    The implementation uses gemm to perform the convolution. This implementation
    is faster than cuDNN for small kernel sizes.
    """
    def __init__(self, in_channels, out_channels, kernel_size, padding=...) -> None:
        ...
    
    def reset_parameters(self): # -> None:
        ...
    
    def conv_tbc(self, input: Tensor): # -> Tensor:
        ...
    
    def forward(self, input: Tensor): # -> Tensor:
        ...
    
    def __repr__(self): # -> str:
        ...
    


