"""
This type stub file was generated by pyright.
"""

import torch.nn as nn
from typing import List, Optional

logger = ...
class FairseqDropout(nn.Module):
    def __init__(self, p, module_name=...) -> None:
        ...
    
    def forward(self, x, inplace: bool = ...): # -> Tensor:
        ...
    
    def make_generation_fast_(self, name: str, retain_dropout: bool = ..., retain_dropout_modules: Optional[List[str]] = ..., **kwargs): # -> None:
        ...
    


