"""
This type stub file was generated by pyright.
"""

import torch.nn as nn

"""
batch norm done in fp32 (for fp16 training)
"""
class Fp32BatchNorm(nn.Module):
    def __init__(self, sync=..., *args, **kwargs) -> None:
        ...
    
    def forward(self, input): # -> Any:
        ...
    


