"""
This type stub file was generated by pyright.
"""

import torch.nn as nn

"""
Layer norm done in fp32 (for fp16 training)
"""
class Fp32InstanceNorm(nn.InstanceNorm1d):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def forward(self, input): # -> Tensor:
        ...
    


