"""
This type stub file was generated by pyright.
"""

import torch

"""
See "Gaussian Error Linear Units (GELUs)" by Dan Hendrycks and Kevin Gimpel with
the corresponding GitHub repo: https://github.com/hendrycks/GELUs
"""
def gelu_accurate(x):
    ...

def gelu(x: torch.Tensor) -> torch.Tensor:
    ...

