"""
This type stub file was generated by pyright.
"""

import torch

class GradMultiply(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, scale):
        ...
    
    @staticmethod
    def backward(ctx, grad): # -> tuple[Any, None]:
        ...
    


