"""
This type stub file was generated by pyright.
"""

import torch.nn as nn
from typing import Dict, Optional
from torch import Tensor

class LearnedPositionalEmbedding(nn.Embedding):
    """
    This module learns positional embeddings up to a fixed maximum size.
    Padding ids are ignored by either offsetting based on padding_idx
    or by setting padding_idx to None and ensuring that the appropriate
    position ids are passed to the forward function.
    """
    def __init__(self, num_embeddings: int, embedding_dim: int, padding_idx: int) -> None:
        ...
    
    def forward(self, input: Tensor, incremental_state: Optional[Dict[str, Dict[str, Optional[Tensor]]]] = ..., positions: Optional[Tensor] = ...): # -> Tensor:
        """Input is expected to be of size [bsz x seqlen]."""
        ...
    


