"""
This type stub file was generated by pyright.
"""

def PositionalEmbedding(num_embeddings: int, embedding_dim: int, padding_idx: int, learned: bool = ...): # -> LearnedPositionalEmbedding | SinusoidalPositionalEmbedding:
    ...

