"""
This type stub file was generated by pyright.
"""

import torch.nn as nn
import torch

class PositionalEncoding(nn.Module):
    """Positional encoding.

    Args:
        d_model: Embedding dimension.
        dropout_rate: Dropout rate.
        max_len: Maximum input length.
        reverse: Whether to reverse the input position.
    """
    def __init__(self, d_model, dropout_rate, max_len=..., reverse=...) -> None:
        """Construct an PositionalEncoding object."""
        ...
    
    def extend_pe(self, x): # -> None:
        """Reset the positional encodings."""
        ...
    
    def forward(self, x: torch.Tensor): # -> Any:
        """Add positional encoding.
        Args:
            x (torch.Tensor): Input tensor B X T X C
        Returns:
            torch.Tensor: Encoded tensor B X T X C
        """
        ...
    


class RelPositionalEncoding(nn.Module):
    """Relative positional encoding module (new implementation).

    Args:
        d_model: Embedding dimension.
        dropout_rate: Dropout rate.
        max_len: Maximum input length.
    """
    def __init__(self, max_len, d_model) -> None:
        """Construct an PositionalEncoding object."""
        ...
    
    def extend_pe(self, x): # -> None:
        """Reset the positional encodings."""
        ...
    
    def forward(self, x: torch.Tensor): # -> Tensor:
        """Add positional encoding.
        Args:
            x : Input tensor T X B X C.
        Returns:
            torch.Tensor: Encoded tensor T X B X C.

        """
        ...
    


