"""
This type stub file was generated by pyright.
"""

from torch import nn

class SamePad(nn.Module):
    def __init__(self, kernel_size, causal=...) -> None:
        ...
    
    def forward(self, x):
        ...
    


