"""
This type stub file was generated by pyright.
"""

import torch

class ScalarBias(torch.autograd.Function):
    """
    Adds a vector of scalars, used in self-attention mechanism to allow
    the model to optionally attend to this vector instead of the past
    """
    @staticmethod
    def forward(ctx, input, dim, bias_init):
        ...
    
    @staticmethod
    def backward(ctx, grad): # -> tuple[Any, None, None]:
        ...
    


def scalar_bias(input, dim, bias_init=...): # -> None:
    ...

