"""
This type stub file was generated by pyright.
"""

import torch.nn as nn

"""
transpose last 2 dimensions of the input
"""
class TransposeLast(nn.Module):
    def __init__(self, deconstruct_idx=...) -> None:
        ...
    
    def forward(self, x):
        ...
    


