"""
This type stub file was generated by pyright.
"""

import torch
from enum import Enum
from typing import Dict, List, Optional, Sequence
from fairseq.data import Dictionary

class EncoderLangtok(Enum):
    """
    Prepend to the beginning of source sentence either the
    source or target language token. (src/tgt).
    """
    src = ...
    tgt = ...


class LangTokSpec(Enum):
    main = ...
    mono_dae = ...


class LangTokStyle(Enum):
    multilingual = ...
    mbart = ...


@torch.jit.export
def get_lang_tok(lang: str, lang_tok_style: str, spec: str = ...) -> str:
    ...

def augment_dictionary(dictionary: Dictionary, language_list: List[str], lang_tok_style: str, langtoks_specs: Sequence[str] = ..., extra_data: Optional[Dict[str, str]] = ...) -> None:
    ...

