"""
This type stub file was generated by pyright.
"""

from typing import List

logger = ...
def uniform(dataset_sizes: List[int]): # -> list[float]:
    ...

def temperature_sampling(dataset_sizes, temp): # -> list[Any]:
    ...

def make_temperature_sampling(temp=...): # -> Callable[..., list[Any]]:
    ...

def make_ratio_sampling(ratios): # -> Callable[..., Any]:
    ...

class SamplingMethod:
    @staticmethod
    def add_arguments(parser): # -> None:
        ...
    
    @staticmethod
    def build_sampler(args, task): # -> SamplingMethod:
        ...
    
    def __init__(self, args, task) -> None:
        ...
    
    def is_adaptive(self): # -> Literal[False]:
        ...
    
    def sampling_method_selector(self): # -> Callable[..., list[float]] | Callable[..., list[Any]] | None:
        ...
    


