[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "UW_StreamSpeech"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.10"
cython = ">=3.0.11,<4"
numpy = ">=2.2.0,<3"

[pypi-dependencies]
torchaudio = ">=2.0.1, <3"
torch = ">=2.0.0, <3"
torchvision = ">=0.15.1, <0.16"
