"""
This type stub file was generated by pyright.
"""

def emulate_int(w, bits, method, scale=..., zero_point=...): # -> Any:
    ...

def quantize(w, scale, zero_point, bits=...):
    ...

def emulate_int8_histogram(w, scale=..., zero_point=..., bits=...): # -> tuple[Tensor | Any, Tensor | Any, Tensor | Any | None]:
    ...

def emulate_int8_channel(w, scale=..., zero_point=..., bits=...): # -> tuple[Any, Any, Any | None]:
    ...

def emulate_int8_tensor(w, scale=..., zero_point=..., bits=...): # -> tuple[Tensor | Any, Tensor | Any, Tensor | Any | None]:
    ...

