"""
This type stub file was generated by pyright.
"""

MAPPING = ...
def quantize_model_(model, p=..., bits=..., update_step=..., method=..., remove_weights=...): # -> list[Any]:
    """
    Replaces all modules with their scalar quantized counterpart and
    registers hooks to quantize the post-ativations of those modules.

    Args:
        - model: a nn.Module
        - p: amount of noise (0 for no noise, 1 to quantize all the weights/activations)
        - bits: number of bits
        - update_step: update quantization parameters every update_step steps
    """
    ...

