"""
This type stub file was generated by pyright.
"""

from fairseq.models.text_to_speech.hifigan import Generator

class CodeGenerator(Generator):
    def __init__(self, cfg) -> None:
        ...
    
    def forward(self, **kwargs): # -> Tensor:
        ...
    


