"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn

LRELU_SLOPE = ...
def init_weights(m, mean=..., std=...): # -> None:
    ...

def get_padding(kernel_size, dilation=...):
    ...

class ResBlock(torch.nn.Module):
    def __init__(self, channels, kernel_size=..., dilation=...) -> None:
        ...
    
    def forward(self, x):
        ...
    
    def remove_weight_norm(self): # -> None:
        ...
    


class Generator(torch.nn.Module):
    def __init__(self, cfg) -> None:
        ...
    
    def forward(self, x): # -> Tensor:
        ...
    
    def remove_weight_norm(self): # -> None:
        ...
    


