"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn
from typing import Dict, Optional, Tuple

logger = ...
class TTSHubInterface(nn.Module):
    def __init__(self, cfg, task, model) -> None:
        ...
    
    @classmethod
    def phonemize(cls, text: str, lang: Optional[str], phonemizer: Optional[str] = ..., preserve_punct: bool = ..., to_simplified_zh: bool = ...): # -> LiteralString | str:
        ...
    
    @classmethod
    def tokenize(cls, text: str, tkn_cfg: Dict[str, str]): # -> str:
        ...
    
    @classmethod
    def update_cfg_with_data_cfg(cls, cfg, data_cfg): # -> None:
        ...
    
    @classmethod
    def get_model_input(cls, task, text: str, speaker: Optional[int] = ..., verbose: bool = ...): # -> dict[str, dict[str, Any | Tensor | None] | Tensor | None]:
        ...
    
    @classmethod
    def get_prediction(cls, task, model, generator, sample) -> Tuple[torch.Tensor, int]:
        ...
    
    def predict(self, text: str, speaker: Optional[int] = ..., verbose: bool = ...) -> Tuple[torch.Tensor, int]:
        ...
    


