"""
This type stub file was generated by pyright.
"""

import ctypes
from dataclasses import dataclass
from fairseq.dataclass import FairseqDataclass
from fairseq.scoring import BaseScorer, register_scorer
from fairseq.scoring.tokenizer import EvaluationTokenizer

class BleuStat(ctypes.Structure):
    _fields_ = ...


@dataclass
class SacrebleuConfig(FairseqDataclass):
    sacrebleu_tokenizer: EvaluationTokenizer.ALL_TOKENIZER_TYPES = ...
    sacrebleu_lowercase: bool = ...
    sacrebleu_char_level: bool = ...


@register_scorer("sacrebleu", dataclass=SacrebleuConfig)
class SacrebleuScorer(BaseScorer):
    def __init__(self, cfg) -> None:
        ...
    
    def add_string(self, ref, pred): # -> None:
        ...
    
    def score(self, order=...): # -> float:
        ...
    
    def result_string(self, order=...): # -> str:
        ...
    


@dataclass
class BleuConfig(FairseqDataclass):
    pad: int = ...
    eos: int = ...
    unk: int = ...


@register_scorer("bleu", dataclass=BleuConfig)
class Scorer:
    def __init__(self, cfg) -> None:
        ...
    
    def reset(self, one_init=...): # -> None:
        ...
    
    def add(self, ref, pred): # -> None:
        ...
    
    def score(self, order=...): # -> float:
        ...
    
    def precision(self): # -> list[Any | int]:
        ...
    
    def brevity(self): # -> float:
        ...
    
    def result_string(self, order=...): # -> str:
        ...
    


