"""
This type stub file was generated by pyright.
"""

SACREBLEU_V2_ABOVE = ...
class EvaluationTokenizer:
    """A generic evaluation-time tokenizer, which leverages built-in tokenizers
    in sacreBLEU (https://github.com/mjpost/sacrebleu). It additionally provides
    lowercasing, punctuation removal and character tokenization, which are
    applied after sacreBLEU tokenization.

    Args:
        tokenizer_type (str): the type of sacreBLEU tokenizer to apply.
        lowercase (bool): lowercase the text.
        punctuation_removal (bool): remove punctuation (based on unicode
        category) from text.
        character_tokenization (bool): tokenize the text to characters.
    """
    SPACE = ...
    SPACE_ESCAPE = ...
    _ALL_TOKENIZER_TYPES = ...
    ALL_TOKENIZER_TYPES = ...
    def __init__(self, tokenizer_type: str = ..., lowercase: bool = ..., punctuation_removal: bool = ..., character_tokenization: bool = ...) -> None:
        ...
    
    @classmethod
    def remove_punctuation(cls, sent: str): # -> str:
        """Remove punctuation based on Unicode category."""
        ...
    
    def tokenize(self, sent: str): # -> str | Any:
        ...
    


