"""
This type stub file was generated by pyright.
"""

from omegaconf import DictConfig

"""isort:skip_file"""
logger = ...
def hydra_init(cfg_name=...) -> None:
    ...

def add_defaults(cfg: DictConfig) -> None:
    """This function adds default values that are stored in dataclasses that hydra doesn't know about"""
    ...

