"""
This type stub file was generated by pyright.
"""

from fairseq.data import Dictionary

class MaskedLMDictionary(Dictionary):
    """
    Dictionary for Masked Language Modelling tasks. This extends Dictionary by
    adding the mask symbol.
    """
    def __init__(self, pad=..., eos=..., unk=..., mask=...) -> None:
        ...
    
    def mask(self): # -> int:
        """Helper to get index of mask symbol"""
        ...
    


class BertDictionary(MaskedLMDictionary):
    """
    Dictionary for BERT task. This extends MaskedLMDictionary by adding support
    for cls and sep symbols.
    """
    def __init__(self, pad=..., eos=..., unk=..., mask=..., cls=..., sep=...) -> None:
        ...
    
    def cls(self): # -> int:
        """Helper to get index of cls symbol"""
        ...
    
    def sep(self): # -> int:
        """Helper to get index of sep symbol"""
        ...
    


