"""
This type stub file was generated by pyright.
"""

from .fairseq_encoder import FairseqEncoder

class CompositeEncoder(FairseqEncoder):
    """
    A wrapper around a dictionary of :class:`FairseqEncoder` objects.

    We run forward on each encoder and return a dictionary of outputs. The first
    encoder's dictionary is used for initialization.

    Args:
        encoders (dict): a dictionary of :class:`FairseqEncoder` objects.
    """
    def __init__(self, encoders) -> None:
        ...
    
    def forward(self, src_tokens, src_lengths): # -> dict[Any, Any]:
        """
        Args:
            src_tokens (LongTensor): tokens in the source language of shape
                `(batch, src_len)`
            src_lengths (LongTensor): lengths of each source sentence of shape
                `(batch)`

        Returns:
            dict:
                the outputs from each Encoder
        """
        ...
    
    def reorder_encoder_out(self, encoder_out, new_order):
        """Reorder encoder output according to new_order."""
        ...
    
    def max_positions(self):
        ...
    
    def upgrade_state_dict(self, state_dict):
        ...
    


