"""
This type stub file was generated by pyright.
"""

logger = ...
_SLOWMO_DDP_DISABLED = ...
def DistributedFairseqModel(args, model, process_group, device): # -> DistributedTimeoutWrapper | ModuleProxyWrapper | Module:
    """
    Wrap a *model* to support distributed data parallel training.

    This is similar to the built-in DistributedDataParallel, but allows
    additional configuration of the DistributedDataParallel class to
    use, and also provides easier access to the wrapped model by
    forwarding requests for missing attributes to the wrapped model.

    Args:
        args (argparse.Namespace): fairseq args
        model (BaseFairseqModel): model to wrap
        process_group: the c10d process group to be used for distributed data
            parallel all-reduction.
        device: device to move model to
    """
    ...

