"""
This type stub file was generated by pyright.
"""

import importlib
import os
import numpy as np
from abc import ABC, abstractmethod
from typing import Dict, Optional

class AudioTransform(ABC):
    @classmethod
    @abstractmethod
    def from_config_dict(cls, config: Optional[Dict] = ...): # -> None:
        ...
    


class CompositeAudioTransform(AudioTransform):
    def __init__(self, transforms) -> None:
        ...
    
    def __call__(self, x):
        ...
    
    def __repr__(self): # -> str:
        ...
    


def register_audio_transform(name, cls_type, registry, class_names): # -> Callable[..., Any]:
    ...

def import_transforms(transforms_dir, transform_type): # -> None:
    ...

def rand_uniform(a, b):
    ...

