"""
This type stub file was generated by pyright.
"""

import importlib
import os
from fairseq import registry
from fairseq.optim.lr_scheduler.fairseq_lr_scheduler import FairseqLRScheduler, LegacyFairseqLRScheduler
from omegaconf import DictConfig

"""isort:skip_file"""
def build_lr_scheduler(cfg: DictConfig, optimizer): # -> Any | None:
    ...

