"""
This type stub file was generated by pyright.
"""

from argparse import Namespace

class FairseqLRScheduler:
    def __init__(self, cfg, optimizer) -> None:
        ...
    
    @classmethod
    def add_args(cls, parser): # -> None:
        """Add arguments to the parser for this LR scheduler."""
        ...
    
    def state_dict(self): # -> dict[str, Any | None]:
        """Return the LR scheduler state dict."""
        ...
    
    def load_state_dict(self, state_dict): # -> None:
        """Load an LR scheduler state dict."""
        ...
    
    def step_begin_epoch(self, epoch): # -> None:
        """Update the learning rate at the beginning of the given epoch."""
        ...
    
    def step(self, epoch, val_loss=...): # -> None:
        """Update the learning rate at the end of the given epoch."""
        ...
    
    def step_update(self, num_updates): # -> Any:
        """Update the learning rate after each update."""
        ...
    


class LegacyFairseqLRScheduler(FairseqLRScheduler):
    def __init__(self, args: Namespace, optimizer) -> None:
        ...
    


