"""
This type stub file was generated by pyright.
"""

import os
from fairseq.data.audio import AudioTransform, CompositeAudioTransform, import_transforms, register_audio_transform

class AudioWaveformTransform(AudioTransform):
    ...


AUDIO_WAVEFORM_TRANSFORM_REGISTRY = ...
AUDIO_WAVEFORM_TRANSFORM_CLASS_NAMES = ...
def get_audio_waveform_transform(name):
    ...

def register_audio_waveform_transform(name): # -> Callable[..., Any]:
    ...

class CompositeAudioWaveformTransform(CompositeAudioTransform):
    @classmethod
    def from_config_dict(cls, config=...): # -> None:
        ...
    
    def __call__(self, x, sample_rate): # -> tuple[Any, Any]:
        ...
    


