"""
This type stub file was generated by pyright.
"""

from fairseq.incremental_decoding_utils import with_incremental_state
from torch import nn
from torch.autograd import Function

class dynamicconvFunction(Function):
    @staticmethod
    def forward(ctx, x, weights, padding_l):
        ...
    
    @staticmethod
    def backward(ctx, grad_output): # -> tuple[Any, Any, None]:
        ...
    


@with_incremental_state
class DynamicconvLayer(nn.Module):
    def __init__(self, input_size, kernel_size=..., padding_l=..., weight_softmax=..., num_heads=..., weight_dropout=..., bias=..., renorm_padding=..., conv_bias=..., query_size=...) -> None:
        ...
    
    def reset_parameters(self): # -> None:
        ...
    
    def forward(self, x, incremental_state=..., query=..., unfold=...): # -> Tensor:
        ...
    
    def reorder_incremental_state(self, incremental_state, new_order): # -> None:
        ...
    


