"""
This type stub file was generated by pyright.
"""

import argparse
import importlib
import os
from fairseq.dataclass import FairseqDataclass
from fairseq.dataclass.utils import merge_with_parent
from hydra.core.config_store import ConfigStore
from .fairseq_task import FairseqTask, LegacyFairseqTask

"""isort:skip_file"""
TASK_DATACLASS_REGISTRY = ...
TASK_REGISTRY = ...
TASK_CLASS_NAMES = ...
def setup_task(cfg: FairseqDataclass, **kwargs):
    ...

def register_task(name, dataclass=...): # -> Callable[..., type[FairseqTask]]:
    """
    New tasks can be added to fairseq with the
    :func:`~fairseq.tasks.register_task` function decorator.

    For example::

        @register_task('classification')
        class ClassificationTask(FairseqTask):
            (...)

    .. note::

        All Tasks must implement the :class:`~fairseq.tasks.FairseqTask`
        interface.

    Args:
        name (str): the name of the task
    """
    ...

def get_task(name):
    ...

def import_tasks(tasks_dir, namespace): # -> None:
    ...

tasks_dir = ...
