"""
This type stub file was generated by pyright.
"""

from fairseq.tasks import LegacyFairseqTask, register_task

logger = ...
@register_task("cross_lingual_lm")
class CrossLingualLMTask(LegacyFairseqTask):
    """
    Task for training cross-lingual language models.

    For more details look at: https://arxiv.org/pdf/1901.07291.pdf

    Args:
        dictionary (Dictionary): the dictionary for the input of the task
    """
    @staticmethod
    def add_args(parser): # -> None:
        """Add task-specific arguments to the parser."""
        ...
    
    def __init__(self, args, dictionary) -> None:
        ...
    
    @classmethod
    def load_dictionary(cls, filename): # -> MaskedLMDictionary:
        ...
    
    @classmethod
    def build_dictionary(cls, filenames, workers=..., threshold=..., nwords=..., padding_factor=...): # -> MaskedLMDictionary:
        ...
    
    @property
    def target_dictionary(self): # -> Any:
        ...
    
    @classmethod
    def setup_task(cls, args, **kwargs): # -> Self:
        """Setup the task."""
        ...
    
    def load_dataset(self, split, epoch=..., combine=..., **kwargs): # -> None:
        """Load a given dataset split.

        Args:
            split (str): name of the split (e.g., train, valid, test)
        """
        ...
    


