"""
This type stub file was generated by pyright.
"""

from fairseq.tasks import register_task
from fairseq.tasks.text_to_speech import TextToSpeechTask

logger = ...
@register_task("frm_text_to_speech")
class FrmTextToSpeechTask(TextToSpeechTask):
    @staticmethod
    def add_args(parser): # -> None:
        ...
    
    def load_dataset(self, split, **unused_kwargs): # -> None:
        ...
    


