"""
This type stub file was generated by pyright.
"""

from fairseq.tasks import register_task
from .denoising import DenoisingTask

logger = ...
@register_task("multilingual_denoising")
class MultilingualDenoisingTask(DenoisingTask):
    @staticmethod
    def add_args(parser): # -> None:
        ...
    
    @classmethod
    def setup_task(cls, args, **kwargs): # -> Self:
        """Setup the task."""
        ...
    
    def __init__(self, args, dictionary) -> None:
        ...
    
    def load_dataset(self, split, epoch=..., combine=..., **kwargs): # -> None:
        """Load a given dataset split.

        Args:
            split (str): name of the split (e.g., train, valid, test)
        """
        ...
    


