"""
This type stub file was generated by pyright.
"""

from fairseq.tasks import LegacyFairseqTask, register_task

logger = ...
@register_task("sentence_ranking")
class SentenceRankingTask(LegacyFairseqTask):
    """
    Ranking task on multiple sentences.

    Args:
        dictionary (Dictionary): the dictionary for the input of the task
    """
    @staticmethod
    def add_args(parser): # -> None:
        """Add task-specific arguments to the parser."""
        ...
    
    def __init__(self, args, dictionary) -> None:
        ...
    
    @classmethod
    def load_dictionary(cls, args, filename, source=...): # -> Dictionary:
        """Load the dictionary from the filename

        Args:
            filename (str): the filename
        """
        ...
    
    @classmethod
    def setup_task(cls, args, **kwargs): # -> FairseqTask:
        ...
    
    def load_dataset(self, split, combine=..., **kwargs):
        """Load a given dataset split (e.g., train, valid, test)."""
        ...
    
    def build_model(self, args, from_checkpoint=...):
        ...
    
    def max_positions(self): # -> Any:
        ...
    
    @property
    def source_dictionary(self): # -> Any:
        ...
    
    @property
    def target_dictionary(self): # -> Any:
        ...
    


