"""
This type stub file was generated by pyright.
"""

from fairseq.tasks import register_task
from fairseq.tasks.speech_to_text import SpeechToTextTask
from fairseq.tasks.translation import TranslationConfig, TranslationTask

import_successful = ...
logger = ...
def check_import(flag): # -> None:
    ...

@register_task("simul_speech_to_text")
class SimulSpeechToTextTask(SpeechToTextTask):
    def __init__(self, args, tgt_dict) -> None:
        ...
    


@register_task("simul_text_to_text", dataclass=TranslationConfig)
class SimulTextToTextTask(TranslationTask):
    def __init__(self, cfg, src_dict, tgt_dict) -> None:
        ...
    


