"""
This type stub file was generated by pyright.
"""

from fairseq.tasks import LegacyFairseqTask, register_task

logger = ...
@register_task("speech_to_text")
class SpeechToTextTask(LegacyFairseqTask):
    @classmethod
    def add_args(cls, parser): # -> None:
        ...
    
    def __init__(self, args, tgt_dict) -> None:
        ...
    
    @classmethod
    def setup_task(cls, args, **kwargs): # -> Self:
        ...
    
    def build_criterion(self, args): # -> Any | None:
        ...
    
    def load_dataset(self, split, epoch=..., combine=..., **kwargs): # -> None:
        ...
    
    @property
    def target_dictionary(self): # -> Any:
        ...
    
    @property
    def source_dictionary(self): # -> None:
        ...
    
    def max_positions(self): # -> tuple[Any, Any]:
        ...
    
    def build_model(self, args, from_checkpoint=...):
        ...
    
    def build_generator(self, models, args, seq_gen_cls=..., extra_gen_cls_kwargs=...): # -> SequenceScorer | SequenceGenerator | SequenceGeneratorWithAlignment:
        ...
    
    def build_tokenizer(self, args): # -> Any | None:
        ...
    
    def build_bpe(self, args): # -> Any | None:
        ...
    
    def get_interactive_tokens_and_lengths(self, lines, encode_fn): # -> tuple[Any, list[int | Any]]:
        ...
    
    def build_dataset_for_inference(self, src_tokens, src_lengths, **kwargs): # -> SpeechToTextDataset:
        ...
    


