"""
This type stub file was generated by pyright.
"""

from .distributed_timeout_wrapper import DistributedTimeoutWrapper
from .fully_sharded_data_parallel import FullyShardedDataParallel, fsdp_enable_wrap, fsdp_wrap
from .legacy_distributed_data_parallel import LegacyDistributedDataParallel
from .module_proxy_wrapper import ModuleProxyWrapper
from .tpu_distributed_data_parallel import TPUDistributedDataParallel

__all__ = ["DistributedTimeoutWrapper", "fsdp_enable_wrap", "fsdp_wrap", "FullyShardedDataParallel", "LegacyDistributedDataParallel", "ModuleProxyWrapper", "TPUDistributedDataParallel"]
