"""
This type stub file was generated by pyright.
"""

from torch import nn

class TPUDistributedDataParallel(nn.Module):
    def __init__(self, module, process_group) -> None:
        ...
    
    def forward(self, *inputs, **kwargs):
        ...
    
    def all_reduce_grads(self): # -> None:
        ...
    


