"""
This type stub file was generated by pyright.
"""

def parse_config_yaml(yaml_data): # -> dict[str, dict[str, list[str | dict[str, int]]] | list[str]]:
    ...

def convert_yaml_to_tuple(yaml_dictionary): # -> tuple[Any, Any]:
    """Converts a yaml dictionary with two keys: `key` and `value` into a two
    argument tuple of those values."""
    ...

