"""
This type stub file was generated by pyright.
"""

import importlib
import os
from abc import ABC, abstractmethod
from typing import Dict, Optional

class AudioFeatureTransform(ABC):
    @classmethod
    @abstractmethod
    def from_config_dict(cls, config: Optional[Dict] = ...): # -> None:
        ...
    


AUDIO_FEATURE_TRANSFORM_REGISTRY = ...
AUDIO_FEATURE_TRANSFORM_CLASS_NAMES = ...
def register_audio_feature_transform(name): # -> Callable[..., type[AudioFeatureTransform]]:
    ...

def get_audio_feature_transform(name):
    ...

transforms_dir = ...
class CompositeAudioFeatureTransform(AudioFeatureTransform):
    @classmethod
    def from_config_dict(cls, config=...): # -> CompositeAudioFeatureTransform | None:
        ...
    
    def __init__(self, transforms) -> None:
        ...
    
    def __call__(self, x):
        ...
    
    def __repr__(self): # -> str:
        ...
    


