"""
This type stub file was generated by pyright.
"""

import os
from fairseq.data.audio import AudioTransform, CompositeAudioTransform, import_transforms, register_audio_transform

class AudioFeatureTransform(AudioTransform):
    ...


AUDIO_FEATURE_TRANSFORM_REGISTRY = ...
AUDIO_FEATURE_TRANSFORM_CLASS_NAMES = ...
def get_audio_feature_transform(name):
    ...

def register_audio_feature_transform(name): # -> Callable[..., Any]:
    ...

class CompositeAudioFeatureTransform(CompositeAudioTransform):
    @classmethod
    def from_config_dict(cls, config=...): # -> None:
        ...
    


