"""
This type stub file was generated by pyright.
"""

from fairseq.data.audio.feature_transforms import AudioFeatureTransform, register_audio_feature_transform

@register_audio_feature_transform("utterance_cmvn")
class UtteranceCMVN(AudioFeatureTransform):
    """Utterance-level CMVN (cepstral mean and variance normalization)"""
    @classmethod
    def from_config_dict(cls, config=...): # -> AudioFeatureTransform:
        ...
    
    def __init__(self, norm_means=..., norm_vars=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __call__(self, x): # -> Any:
        ...
    


