"""
This type stub file was generated by pyright.
"""

import importlib
import os
from fairseq import registry
from fairseq.criterions.fairseq_criterion import FairseqCriterion, LegacyFairseqCriterion
from omegaconf import DictConfig

"""isort:skip_file"""
def build_criterion(cfg: DictConfig, task): # -> Any | None:
    ...

