"""
This type stub file was generated by pyright.
"""

from fairseq.models import FairseqEncoder

class CTCDecoder(FairseqEncoder):
    def __init__(self, dictionary, in_dim) -> None:
        ...
    
    def forward(self, src_tokens, src_lengths=..., **kwargs): # -> dict[str, Any]:
        ...
    


