"""
This type stub file was generated by pyright.
"""

from torch import nn

class StackedEmbedding(nn.Embedding):
    """Embedding module that supports stacked units -> single embedding"""
    def __init__(self, num_embeddings, embed_dim, padding_idx, num_stacked=...) -> None:
        ...
    
    def forward(self, input): # -> Tensor:
        ...
    


