"""
This type stub file was generated by pyright.
"""

from fairseq.models import FairseqEncoder

class TransformerEncoderNoEmb(FairseqEncoder):
    """Transformer encoder without token embeddings."""
    def __init__(self, args) -> None:
        ...
    
    def forward(self, x, encoder_padding_mask, return_all_hiddens=...): # -> dict[str, list[Any]]:
        ...
    
    def reorder_encoder_out(self, encoder_out, new_order): # -> dict[str, list[Any] | Any]:
        ...
    


