"""
This type stub file was generated by pyright.
"""

import typing as tp

def find_offsets(filename: str, num_chunks: int) -> tp.List[int]:
    """
    given a file and a number of chuncks, find the offsets in the file
    to be able to chunk around full lines.
    """
    ...

class ChunkLineIterator:
    """
    Iterator to properly iterate over lines of a file chunck.
    """
    def __init__(self, fd, start_offset: int, end_offset: int) -> None:
        ...
    
    def __iter__(self) -> tp.Iterable[str]:
        ...
    


class Chunker:
    """
    contextmanager to read a chunck of a file line by line.
    """
    def __init__(self, path: str, start_offset: int, end_offset: int) -> None:
        ...
    
    def __enter__(self) -> ChunkLineIterator:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        ...
    


