"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from torch import Tensor

class FairseqIncrementalState:
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def init_incremental_state(self): # -> None:
        ...
    
    def get_incremental_state(self, incremental_state: Optional[Dict[str, Dict[str, Optional[Tensor]]]], key: str) -> Optional[Dict[str, Optional[Tensor]]]:
        """Helper for getting incremental state for an nn.Module."""
        ...
    
    def set_incremental_state(self, incremental_state: Optional[Dict[str, Dict[str, Optional[Tensor]]]], key: str, value: Dict[str, Optional[Tensor]]) -> Optional[Dict[str, Dict[str, Optional[Tensor]]]]:
        """Helper for setting incremental state for an nn.Module."""
        ...
    


def with_incremental_state(cls):
    ...

