"""
This type stub file was generated by pyright.
"""

logger = ...
class NanDetector:
    """
    Detects the first NaN or Inf in forward and/or backward pass and logs, together with the module name
    """
    def __init__(self, model, forward=..., backward=...) -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, exc_type, exc_value, exc_traceback): # -> None:
        ...
    
    def add_hooks(self, module): # -> None:
        ...
    
    def reset(self): # -> None:
        ...
    
    def fhook_fn(self, module, inp, output): # -> None:
        ...
    
    def bhook_fn(self, module, inp, output): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    


