"""
This type stub file was generated by pyright.
"""

import torch
from torch import nn

""" Wrapper for ngram_repeat_block cuda extension """
EXTENSION_BUILT = ...
def is_cuda_extension_usable() -> bool:
    """Check whether ngram_repeat_block_cuda is built properly"""
    ...

class NGramRepeatBlock(nn.Module):
    """Wrapper class for calling ngram_repeat_block cuda extension"""
    def __init__(self, no_repeat_ngram_size: int, use_extension: bool = ...) -> None:
        ...
    
    def reset_parameters(self): # -> None:
        ...
    
    @torch.jit.unused
    def call_cuda_extension(self, tokens, lprobs, bsz: int, beam_size: int, step: int):
        ...
    
    def forward(self, tokens, lprobs, bsz: int, beam_size: int, step: int):
        """
        Args:
            tokens(Tensor): Input tokens(Bsz*beam, seq_len)
            lprobs(Tensor): likelihood probability,
            Expected to be updated in place.(Bsz*beam, vocab_size)
            bsz(int): batch size
            step(int): current step
            beam_size(int): beam size
            no_repeat_ngram_size(int): Ngram size
        """
        ...
    


