"""
This type stub file was generated by pyright.
"""

import pdb

__all__ = ["set_trace"]
_stdin = ...
_stdin_lock = ...
_stdin_fd = ...
class MultiprocessingPdb(pdb.Pdb):
    """A Pdb wrapper that works in a multiprocessing environment.

    Usage: `from fairseq import pdb; pdb.set_trace()`
    """
    def __init__(self) -> None:
        ...
    


def set_trace(): # -> None:
    ...

