"""
This type stub file was generated by pyright.
"""

from omegaconf import DictConfig

logger = ...
def quantize_model_scalar(model, model_cfg: DictConfig):
    ...

class Quantizer:
    def __init__(self, config_path, max_epoch, max_update) -> None:
        ...
    
    def set_trainer(self, trainer): # -> None:
        ...
    
    def step(self): # -> None:
        """Move to the next stage of quantization."""
        ...
    
    def begin_epoch(self, epoch): # -> None:
        """Called at the beginning of each epoch (epochs start at 1)."""
        ...
    
    def step_update(self, num_updates): # -> None:
        """Called at the end of each step."""
        ...
    
    def state_dict(self): # -> dict[str, dict[str, list[str | dict[str, int]]] | list[str] | Any | int | None]:
        ...
    
    def load_state_dict(self, state_dict): # -> None:
        ...
    


