"""
This type stub file was generated by pyright.
"""

REGISTRIES = ...
def setup_registry(registry_name: str, base_class=..., default=..., required=...): # -> tuple[Callable[..., Any | None], Callable[..., Callable[..., Any]], dict[Any, Any], dict[Any, Any]] | None:
    ...

