"""
This type stub file was generated by pyright.
"""

import torch
from fairseq.data.audio.speech_to_text_dataset import S2TDataConfig

class SpeechGenerator:
    def __init__(self, model, vocoder, data_cfg: S2TDataConfig) -> None:
        ...
    
    def gcmvn_denormalize(self, x):
        ...
    
    def get_waveform(self, feat): # -> None:
        ...
    


class AutoRegressiveSpeechGenerator(SpeechGenerator):
    def __init__(self, model, vocoder, data_cfg, max_iter: int = ..., eos_prob_threshold: float = ...) -> None:
        ...
    
    @torch.no_grad()
    def generate(self, model, sample, has_targ=..., **kwargs): # -> list[dict[str, Any | Tensor | None]]:
        ...
    


class NonAutoregressiveSpeechGenerator(SpeechGenerator):
    @torch.no_grad()
    def generate(self, model, sample, has_targ=..., **kwargs): # -> list[dict[str, Any | None]]:
        ...
    


class TeacherForcingAutoRegressiveSpeechGenerator(AutoRegressiveSpeechGenerator):
    @torch.no_grad()
    def generate(self, model, sample, has_targ=..., **kwargs): # -> list[dict[str, Any | None]]:
        ...
    


