"""
This type stub file was generated by pyright.
"""

from enum import Enum

class TextCompressionLevel(Enum):
    none = ...
    low = ...
    high = ...


class TextCompressor:
    def __init__(self, level: TextCompressionLevel, max_input_byte_length: int = ...) -> None:
        ...
    
    def compress(self, text: str) -> bytes:
        ...
    
    def decompress(self, compressed: bytes) -> str:
        ...
    


