"""
This type stub file was generated by pyright.
"""

from torch import nn
from fairseq.models import FairseqEncoder

class CTCDecoder(FairseqEncoder):
    def __init__(self, dictionary, in_dim) -> None:
        ...
    
    def forward(self, src_tokens, src_lengths=..., **kwargs): # -> dict[str, Any]:
        ...
    


class StackedEmbedding(nn.Embedding):
    """Embedding module that supports stacked units -> single embedding"""
    def __init__(self, num_embeddings, embed_dim, padding_idx, num_stacked=...) -> None:
        ...
    
    def forward(self, input): # -> Tensor | Any:
        ...
    


