"""
This type stub file was generated by pyright.
"""

from fairseq.models import register_model, register_model_architecture
from fairseq.models.speech_to_speech.s2s_conformer import S2SpecTConformerModel

logger = ...
@register_model("s2spect2_conformer")
class S2SpecT2ConformerModel(S2SpecTConformerModel):
    """
    Direct speech-to-speech translation model with Conformer encoder + MT Transformer decoder + TTS Transformer decoder
    """
    @staticmethod
    def add_args(parser): # -> None:
        ...
    
    @classmethod
    def build_multitask_decoder(cls, args, tgt_dict, in_dim, is_mt_decoder, decoder_layers, decoder_embed_dim, decoder_attention_heads): # -> TransformerDecoder | CTCDecoder:
        ...
    
    @classmethod
    def build_decoder(cls, args): # -> TTSTransformerDecoder:
        ...
    
    @classmethod
    def build_model(cls, args, task): # -> Self:
        ...
    
    @classmethod
    def build_text_encoder(cls, args): # -> TransformerEncoderNoEmb:
        ...
    
    def forward(self, src_tokens, src_lengths, prev_output_tokens, prev_output_tokens_mt, tgt_speaker=..., incremental_state=..., target_lengths=..., speaker=..., return_all_hiddens=...): # -> Any:
        ...
    


@register_model_architecture(model_name="s2spect2_conformer", arch_name="s2spect2_conformer")
def s2spect2_conformer_architecture_base(args): # -> None:
    ...

@register_model_architecture(model_name="s2spect2_conformer", arch_name="s2spect_conformer_translatotron2")
def s2spect2_conformer_architecture_base_legacy(args): # -> None:
    ...

