"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn
from typing import Optional, Tuple, Union

logger = ...
class S2THubInterface(nn.Module):
    def __init__(self, cfg, task, model) -> None:
        ...
    
    @classmethod
    def get_model_input(cls, task, audio: Union[str, torch.Tensor]): # -> dict[str, dict[str, Tensor | None] | None]:
        ...
    
    @classmethod
    def detokenize(cls, task, tokens): # -> Any:
        ...
    
    @classmethod
    def get_prefix_token(cls, task, lang): # -> Tensor | None:
        ...
    
    @classmethod
    def get_prediction(cls, task, model, generator, sample, tgt_lang=..., synthesize_speech=...) -> Union[str, Tuple[str, Tuple[torch.Tensor, int]]]:
        ...
    
    def predict(self, audio: Union[str, torch.Tensor], tgt_lang: Optional[str] = ..., synthesize_speech: bool = ...) -> Union[str, Tuple[str, Tuple[torch.Tensor, int]]]:
        ...
    


