"""
This type stub file was generated by pyright.
"""

from fairseq.models import FairseqDecoder, FairseqEncoder

class MultiModalityEncoder(FairseqEncoder):
    def __init__(self, dictionary) -> None:
        ...
    
    def select_encoder(self, mode, **kwargs):
        ...
    
    def forward(self, src_tokens, src_lengths=..., mode=..., **kwargs):
        ...
    


class MultiInputDecoder(FairseqDecoder):
    def __init__(self, dictionary) -> None:
        ...
    
    def select_decoder(self, mode, **kwargs):
        ...
    
    def forward(self, prev_output_tokens, encoder_out, incremental_state=..., mode=..., **kwargs):
        ...
    


