"""
This type stub file was generated by pyright.
"""

from fairseq.models import FairseqEncoder

class SpeechWavTransformerEncoder(FairseqEncoder):
    @staticmethod
    def add_args(parser): # -> None:
        ...
    
    def __init__(self, args, alway_mask=...) -> None:
        ...
    
    def apply_mask(self, x, padding_mask): # -> tuple[Any, Tensor | None]:
        ...
    
    def forward(self, src_tokens, src_lengths, return_all_hiddens=..., padding_mask=..., features_only=...): # -> dict[str, list[Any] | list[Tensor] | list[Tensor | None]] | dict[str, list[Any] | list[Tensor]]:
        ...
    
    def reorder_encoder_out(self, encoder_out, new_order): # -> dict[str, list[Any] | Any]:
        ...
    


class StackedSpeechWavTransformerEncoder(FairseqEncoder):
    def __init__(self, speech_enc, text_enc_layers, text_layer_norm) -> None:
        ...
    
    def forward(self, src_tokens, src_lengths=..., return_all_hiddens=..., padding_mask=..., features_only=...): # -> dict[str, list[Any]] | dict[str, list[Any] | Any]:
        ...
    
    def reorder_encoder_out(self, encoder_out, new_order):
        ...
    


