"""
This type stub file was generated by pyright.
"""

import importlib
import os
from fairseq import registry
from fairseq.optim.bmuf import FairseqBMUF
from fairseq.optim.fairseq_optimizer import FairseqOptimizer, LegacyFairseqOptimizer
from fairseq.optim.amp_optimizer import AMPOptimizer
from fairseq.optim.fp16_optimizer import FP16Optimizer, MemoryEfficientFP16Optimizer
from fairseq.optim.shard import shard_
from omegaconf import DictConfig

"""isort:skip_file"""
__all__ = ["AMPOptimizer", "FairseqOptimizer", "FP16Optimizer", "MemoryEfficientFP16Optimizer", "shard_"]
def build_optimizer(cfg: DictConfig, params, *extra_args, **extra_kwargs): # -> Any | None:
    ...

