"""
This type stub file was generated by pyright.
"""

class DynamicLossScaler:
    def __init__(self, init_scale=..., scale_factor=..., scale_window=..., tolerance=..., threshold=..., min_loss_scale=...) -> None:
        ...
    
    def scale(self, outputs):
        ...
    
    def update(self): # -> None:
        ...
    
    def check_overflow(self, grad_norm): # -> None:
        ...
    


