"""
This type stub file was generated by pyright.
"""

from fairscale.optim import OSS

_has_fairscale = ...
def shard_(optimizer, group): # -> None:
    class FairseqOSS(OSS):
        ...
    
    

